import Vue from 'vue';
import Vuetify, {
  VApp,
  VAvatar,
  VBtn,
  VCard,
  VCardActions,
  VCardTitle,
  VContainer,
  VContent,
  VFlex,
  VIcon,
  VLayout,
  VList,
  VListTile,
  VListTileAction,
  VListTileContent,
  VListTileTitle,
  VNavigationDrawer,
  VSpacer,
  VTextField,
  VToolbar,
  VToolbarTitle,
  VToolbarSideIcon,
  VTooltip,
} from 'vuetify/lib';
import 'vuetify/src/stylus/app.styl';

Vue.use(Vuetify, {
  iconfont: 'md',
  components: {
    VApp,
    VAvatar,
    VBtn,
    VCard,
    VCardActions,
    VCardTitle,
    VContainer,
    VContent,
    VFlex,
    VIcon,
    VLayout,
    VList,
    VListTile,
    VListTileAction,
    VListTileContent,
    VListTileTitle,
    VNavigationDrawer,
    VSpacer,
    VTextField,
    VToolbar,
    VToolbarTitle,
    VToolbarSideIcon,
    VTooltip,
  },
});
